# This is a basic workflow to help you get started with Actions

name: test


concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  #workflow_run:
  #  workflows: [CI2]
  #  types: [completed]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
#   on_success:

    runs-on: ubuntu-latest
    environment: testing
    env:
      TOKEN: ${{ secrets.TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}
      MONGOPW: ${{ secrets.MONGOPW }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3




      # Runs a set of commands using the runners shell
      - name: import
        run: |
          python -m pip install hikari
          python -m hikari
          python -m pip install hikari-miru
          python -m pip install openai
          python -m pip install hikari-lightbulb
          python -m pip install flask
          python -m pip install datetime
          python -m pip install schedule
          python -m pip install pymongo
          
      # Runs a single command using the runners shell
      - name: Run main.py
        run: python main.py
#      - name: Push after run
#        run: git push
